# Generated by Django 3.2.13 on 2022-05-29 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cipher', models.CharField(default=None, max_length=233)),
                ('depth', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnedCipher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned', models.CharField(default='', max_length=245)),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seed1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_1', models.IntegerField(default=1)),
                ('seed_2', models.IntegerField(default=1)),
                ('inherited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payloads.returnedcipher')),
            ],
        ),
    ]
